spring:
  application:
    name: warehouse
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:9432/warehouse-db
    username: db
    password: db
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate:
      jdbc.time_zone: UTC
      format_sql: true
      temp.use_jdbc_metadata_defaults: false
    hibernate.ddl-auto: create
    show-sql: false
  sql.init.mode: always

logging:
  level:
    ru.yandex.practicum.commerce: TRACE
    org:
      springframework: ERROR
      springframework.cloud.netflix.eureka: INFO