server:
  port: 0

spring:
  application:
    name: payment
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:2432/payment-db
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate:
      jdbc.time_zone: UTC
      format_sql: true
      temp.use_jdbc_metadata_defaults: false
    hibernate.ddl-auto: none
    show-sql: false
  sql.init.mode: always

logging:
  level:
    ru.yandex.practicum.commerce: TRACE
    org:
      springframework: ERROR
      springframework.cloud.netflix.eureka: INFO