server:
  port: 8081

spring:
  application:
    name: telemetry-aggregator

aggregator:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      topic: telemetry.snapshots.v1
      properties:
        bootstrap.servers: localhost:9092
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
        linger.ms: 0
        acks: all
        retries: 3
        max.in.flight.requests.per.connection: 5
        batch.size: 16384
        buffer.memory: 33554432
        compression.type: snappy

      consumer:
        topic: telemetry.sensors.v1
        poll-timeout: 500ms
        properties:
          bootstrap.servers: localhost:9092
          enable.auto.commit: false
          group.id: telemetry.aggregator.sensors
          key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value.deserializer: ru.yandex.practicum.kafka.deserializer.SensorEventDeserializer
          auto.offset.reset: earliest
          max.poll.records: 100
          max.poll.interval.ms: 300000
          session.timeout.ms: 30000
          heartbeat.interval.ms: 3000

logging:
  level:
    ru.yandex.practicum.telemetry.aggregator: INFO
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"