spring:
  application:
    name: analyzer
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
      jdbc:
        time_zone: UTC
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6541/analyzer
    username: db
    password: db

logging:
  level:
    ru.yandex.practicum.telemetry: TRACE
    org.springframework: ERROR
    org.springframework.cloud.netflix.eureka: INFO
    apache.kafka: WARN

grpc:
  client:
    hub-router:
      address: static://localhost:59090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

analyzer:
  kafka:
    common-properties:
      bootstrap.servers: localhost:9092
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable.auto.commit: false
    consumers:
      -
        type: SnapshotProcessor
        properties:
          value.deserializer: ru.yandex.practicum.kafka.deserializer.SensorsSnapshotDeserializer
          group.id: telemetry.analyzer.snapshot
        topics:
          - telemetry.snapshots.v1
        poll-timeout: 500ms
      -
        type: HubEventProcessor
        properties:
          value.deserializer: ru.yandex.practicum.kafka.deserializer.HubEventDeserializer
          group.id: telemetry.analyzer.hub
        topics:
          - telemetry.hubs.v1
        poll-timeout: 2000ms